# Generated by Django 4.2.3 on 2023-08-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0004_alter_advertisement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Опубликовано'),
        ),
    ]
