# Generated by Django 4.2.3 on 2023-08-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0005_alter_advertisement_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='deskription',
            new_name='description',
        ),
    ]
