# Generated by Django 4.2.3 on 2023-08-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0010_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='advertisements/', verbose_name='Изображение'),
        ),
    ]
